server:
  port: 8080

spring:
  #thymeleaf模板信息设置
  thymeleaf:
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    check-template: true
    enabled: true

  mvc:
    #不使用SpringBoot默认图标
    favicon:
      enabled: false
    #静态资源路径
    static-path-pattern: /static/**
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management-system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:

    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化
      initialSize: 3
      # 最大
      maxActive: 20
      # 最小
      minIdle: 3
      # 最大连接等待超时时间
      maxWait: 60000
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
  #Data Jpa
  jpa:
    hibernate:
      # 实体类有更新时，数据库表更新
      ddl-auto: update
    #打印sql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

